// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0v_TFBkJmf572UTS8cDf5UuOFDK8a4wQ',
    appId: '1:766797793113:web:60459c8a98410be2566e48',
    messagingSenderId: '766797793113',
    projectId: 'rickoins',
    authDomain: 'rickoins.firebaseapp.com',
    databaseURL: 'https://rickoins-default-rtdb.firebaseio.com',
    storageBucket: 'rickoins.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDH7sT6nMX9oQO74NaE52OD-8kf8qFapc',
    appId: '1:766797793113:android:39c5ba095625aab3566e48',
    messagingSenderId: '766797793113',
    projectId: 'rickoins',
    databaseURL: 'https://rickoins-default-rtdb.firebaseio.com',
    storageBucket: 'rickoins.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLeZJztxFvrNvz3yNpUFpeCV9Ym41uTi0',
    appId: '1:766797793113:ios:69ee86e64ff9f4be566e48',
    messagingSenderId: '766797793113',
    projectId: 'rickoins',
    databaseURL: 'https://rickoins-default-rtdb.firebaseio.com',
    storageBucket: 'rickoins.firebasestorage.app',
    iosBundleId: 'com.example.rickoins',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLeZJztxFvrNvz3yNpUFpeCV9Ym41uTi0',
    appId: '1:766797793113:ios:69ee86e64ff9f4be566e48',
    messagingSenderId: '766797793113',
    projectId: 'rickoins',
    databaseURL: 'https://rickoins-default-rtdb.firebaseio.com',
    storageBucket: 'rickoins.firebasestorage.app',
    iosBundleId: 'com.example.rickoins',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0v_TFBkJmf572UTS8cDf5UuOFDK8a4wQ',
    appId: '1:766797793113:web:cf7a92bf08664aff566e48',
    messagingSenderId: '766797793113',
    projectId: 'rickoins',
    authDomain: 'rickoins.firebaseapp.com',
    databaseURL: 'https://rickoins-default-rtdb.firebaseio.com',
    storageBucket: 'rickoins.firebasestorage.app',
  );

}